Development
Zibilyonik/Gradient-Background pull request #1
Opened 2019-05-05 10:10 UTC by Zibilyonik

2019-05-05 14:02 UTC, oluwoleilesanmi requested changes
@Zibilyonik well done good work on this project it is good you are using a reset.css and your project structure is really good.make the changes below and you will be good to go.

- The navigation bar is not in place
![](https://res.cloudinary.com/drw0cxkwk/image/upload/v1557063452/broken2_x7nkjg.png)

2019-05-05 14:02 UTC, oluwoleilesanmi commented on assets/CSS/style.css
> +  background-image: url("../images/your_verse_hero_2x.jpg");
- Include this resource in remote storage like [Cloudinary](https://cloudinary.com) so it is displayed on [github previewer](https://htmlpreview.github.io)
- See how it looks on github previewer below there is no hero image displayed
![broken](https://res.cloudinary.com/drw0cxkwk/image/upload/v1557063449/broken_nkhx0j.png)
- To recreate this issue copy [Link](https://github.com/Zibilyonik/Gradient-Background/blob/development/index.html) and paste in [github previewer](https://htmlpreview.github.io)
- Reason to fix this is because not everyone will clone your project to see how it looks.

2019-05-06 13:00 UTC, Zibilyonik commented on assets/CSS/style.css
> +  background-image: url("../images/your_verse_hero_2x.jpg");
I'll try to use it but right now I don't have much time to focus on it. I'm trying to finish the last project to get to Ruby with my partner so after we finish it I can take a look at how to implement it into my projects.

2019-05-06 21:59 UTC, oluwoleilesanmi commented on assets/CSS/style.css
> +  background-image: url("../images/your_verse_hero_2x.jpg");
Thats ok, this is not a mandatory requirement. feel free to improve application you have written even after getting thumbs up.

2019-05-06 22:20 UTC, oluwoleilesanmi approved these changes
@Zibilyonik well done please change below css property, it does not require you to resubmit but make the correction before moving to next project. :+1: proceed.

2019-05-06 22:20 UTC, oluwoleilesanmi commented on assets/CSS/style.css
> +  top:200px;
- Replace with `top:50px;` the nav-bar is too low with the 200px set.

2019-05-09 09:06 UTC, merged